#!/bin/sh

set -e

if [ "$1" = configure ]; then
  update-alternatives --install /usr/share/lightdm-webkit/themes/default \
    lightdm-webkit-theme /usr/share/lightdm-webkit/themes/manokwari-theme-greeter 50
fi

#DEBHELPER#
