libreoffice/backing_left-edusantara.png /usr/lib/libreoffice/program/shell/
libreoffice/backing_right-edusantara.png /usr/lib/libreoffice/program/shell/
libreoffice/backing_rtl_left-edusantara.png /usr/lib/libreoffice/program/shell/
libreoffice/backing_rtl_right-edusantara.png /usr/lib/libreoffice/program/shell/
libreoffice/backing_space-edusantara.png /usr/lib/libreoffice/program/shell/
libreoffice/intro-edusantara.png /usr/lib/libreoffice/program/
libreoffice/flat_logo-edusantara.svg /usr/lib/libreoffice/program/
libreoffice/sofficerc-edusantara /etc/libreoffice/
