#! /bin/sh
set -e

if [ -f /usr/lib/blankon-installer/system/index.html.divert ]; then
  rm -f /usr/lib/blankon-installer/system/index.html
  dpkg-divert --local --remove --rename /usr/lib/blankon-installer/system/index.html
fi
if [ -f /usr/lib/blankon-installer/system/logo.png.divert ]; then
  rm -f /usr/lib/blankon-installer/system/logo.png
  dpkg-divert --local --remove --rename /usr/lib/blankon-installer/system/logo.png
fi
if [ -f /usr/share/applications/blankon-installer.desktop.divert ]; then
  rm -f /usr/share/applications/blankon-installer.desktop
  dpkg-divert --local --remove --rename /usr/share/applications/blankon-installer.desktop
fi
#if [ -f /usr/share/locale/id/LC_MESSAGES/blankon-installer.mo.divert ]; then
#  rm -f /usr/share/locale/id/LC_MESSAGES/blankon-installer.mo
#  dpkg-divert --local --remove --rename /usr/share/locale/id/LC_MESSAGES/blankon-installer.mo
#fi
